spring.application.name=docmind

spring.datasource.url=jdbc:postgresql://localhost:5432/docmind
spring.datasource.username=docmind
spring.datasource.password=docmind

spring.jpa.hibernate.ddl-auto=update